shop/cart/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^shopAdmin/category/create/$',
        AdminCategoryCreateView.as_view(), name="adminCategoryCreate"),
    url(r'^shopAdmin/category/(?P<pk>\d+)/update/$',
        AdminCategoryUpdateView.as_view(), name="adminCategoryUpdate"),
    url(r'^shopAdmin/category/list/$',
        AdminCategoryListView.as_view(), name="adminCategoryList"),


    url(r'^shopAdmin/coupon/create/$',
        AdminCouponCreateView.as_view(), name="adminCouponCreate"),
    url(r'^shopAdmin/coupon/list/$',
        AdminCouponListView.as_view(), name="adminCouponList"),
    url(r'^shopAdmin/coupon/(?P<pk>\d+)/update/$',
        AdminCouponUpdateView.as_view(), name='adminCouponUpdate'),
    url(r'^shopAdmin/coupon/(?P<pk>\d+)/update/$',
        AdminCouponUpdateView.as_view(), name='adminCouponUpdate'),

    url(r'^shopAdmin/product/create/$',
        AdminProductCreateView.as_view(), name="adminProductCreate"),

    url(r'^shopAdmin/siteconfig/create/$',
        AdminSiteConfigCreateView.as_view(), name="adminSiteConfigCreate"),
    url(r'^shopAdmin/siteconfig/list/$',
        AdminSiteConfigListView.as_view(), name="adminSiteConfigList"),
    url(r'^shopAdmin/siteconfig/(?P<pk>\d+)/update/$',
        AdminSiteConfigUpdateView.as_view(), name="adminSiteConfigUpdate"),
]

shop/messaging/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^admin/$',
        AdminMessage.as_view(), name="adminMessage"),
    url(r'^admin/(?P<slug>[\w-]+)/$',
        AdminMessage.as_view(), name="adminMessage"),
]

shop/shop/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^messages/', include('messaging.urls', namespace='message')),
    url(r'', include('account.urls', namespace='account')),
    url(r'', include('cart.urls', namespace='cart')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/templates/layouts/admin/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>{% block head_title %}Admin Pannel{% endblock %}</title>
    {% include "layouts/admin/include/head.html" %}
    {% block extra_head %}
    {% endblock %}
</head>
<body class="menubar-hoverable header-fixed full-content">
    <!-- BEGIN HEADER-->
    <header id="header" >
        <div class="headerbar">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="headerbar-left">
                <ul class="header-nav header-nav-options">
                    <li class="header-nav-brand" >
                        <div class="brand-holder">
                            <a href="#">
                                <span class="text-lg text-bold text-primary">ADMIN PANNEL</span>
                            </a>
                        </div>
                    </li>
                    <li>
                        <a class="btn btn-icon-toggle menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                            <i class="fa fa-bars"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="headerbar-right">
                <ul class="header-nav header-nav-options">
                    <li>
                        <!-- Search form -->
                        <form class="navbar-search" role="search">
                            <div class="form-group">
                                <input type="search" class="form-control" name="headerSearch" placeholder="Enter your keyword">
                            </div>
                            <button type="submit" class="btn btn-icon-toggle ink-reaction"><i class="fa fa-search"></i></button>
                        </form>
                    </li>
                </ul><!--end .header-nav-options -->
                <ul class="header-nav header-nav-profile">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle ink-reaction" data-toggle="dropdown">
                            <img src="{% static 'assets/img/avatar1.jpg' %}" alt="" />
                            <span class="profile-info">
                                {{request.user.get_full_name}}
                                <small> Administrator</small>
                            </span>
                        </a>
                        <ul class="dropdown-menu animation-dock">
                            <li class="dropdown-header">Config</li>
                            <li><a href="#">My profile</a></li>
                            <li><a href="#">My blog <span class="badge style-danger pull-right">16</span></a></li>
                            <li><a href="#">My appointments</a></li>
                            <li class="divider"></li>
                            <li><a href="#"><i class="fa fa-fw fa-envelope"></i> Change Email</a></li>
                            <li><a href="#"  data-toggle="modal" data-target="#logOutModal"><i class="fa fa-fw fa-power-off text-danger"></i> Logout</a></li>
                        </ul><!--end .dropdown-menu -->
                    </li><!--end .dropdown -->
                </ul><!--end .header-nav-profile -->
            </div><!--end #header-navbar-collapse -->
        </div>
    </header>
    <!-- END HEADER-->

    <div class="modal fade" id="logOutModal" tabindex="-1" role="dialog" aria-labelledby="logOutModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="simpleModalLabel">Log Out</h4>
                </div>
                <div class="modal-body">
                    <p>Do you want to logout?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary"><a href="#"  style="text-decoration:none;">Logout</a></button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- END SIMPLE MODAL MARKUP -->


    <!-- BEGIN BASE-->
    <div id="base">
        {% if messages %}
        {% for message in messages %}
        <div id="toast-container" class="toast-bottom-right" aria-live="polite" role="alert">
           <div class="toast toast-{{message.tags}}">
               <div class="toast-message">{{ message }}</div>
           </div>
       </div>
       {% endfor %}
       {% endif %}
       <!-- BEGIN CONTENT-->
       <div id="content">
        {% block content %}
        {% endblock %}
    </div><!--end #content-->
    <!-- END CONTENT -->
    {% block menubar%}
    <!-- BEGIN MENUBAR-->
    <div id="menubar" class="menubar-inverse ">
        <div class="menubar-fixed-panel">
            <div>
                <a class="btn btn-icon-toggle btn-default menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                    <i class="fa fa-bars"></i>
                </a>
            </div>
            <div class="expanded">
                <a href="#">
                    <span class="text-lg text-bold text-primary ">SHARIFA&nbsp;ADMIN</span>
                </a>
            </div>
        </div>
        <div class="menubar-scroll-panel">

            <!-- BEGIN MAIN MENU -->
            <ul id="main-menu" class="gui-controls">

                <!-- BEGIN DASHBOARD -->
                <li>
                    <a href="#">
                        <div class="gui-icon"><i class="fa fa-home"></i></div>
                        <span class="title">Dashboard</span>
                    </a>
                </li><!--end /menu-li -->
                <!-- END DASHBOARD -->

                <li>
                    <a href="{% url 'message:adminMessage'%}" id="message">
                        <div class="gui-icon"><i class="fa fa-envelope"></i></div>
                        <span class="title">Message</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="#">
                        <div class="gui-icon"><i class="fa fa-th-list"></i></div>
                        <span class="title">Product</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="#">
                        <div class="gui-icon"><i class="md md-web"></i></div>
                        <span class="title">Category</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="#">
                        <div class="gui-icon"><i class="fa fa-barcode"></i></div>
                        <span class="title">Tags</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="#">
                        <div class="gui-icon"><i class="md md-assignment"></i></div>
                        <span class="title">Users</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="#">
                        <div class="gui-icon"><i class="fa fa-calendar"></i></div>
                        <span class="title">Coupons</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="#">
                        <div class="gui-icon"><i class="fa fa-calendar"></i></div>
                        <span class="title">Slider</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="#">
                        <div class="gui-icon"><i class="fa fa-calendar"></i></div>
                        <span class="title">Photo</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="#">
                        <div class="gui-icon"><i class="md md-shopping-cart"></i></div>
                        <span class="title">Order</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="#">
                        <div class="gui-icon"><i class="fa fa-gears"></i></div>
                        <span class="title">Site Config</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="#">
                        <div class="gui-icon"><i class="fa fa-users"></i></div>
                        <span class="title">Staff</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="#">
                        <div class="gui-icon"><i class="fa fa-users"></i></div>
                        <span class="title">User</span>
                    </a>
                </li><!--end /menu-li -->


            </ul><!--end .main-menu -->
            <!-- END MAIN MENU -->

            <div class="menubar-foot-panel">
                <small class="no-linebreak hidden-folded">
                    <span class="opacity-75">Copyright &copy; 2016</span> <strong>Prixa</strong>
                </small>
            </div>
        </div><!--end .menubar-scroll-panel-->
    </div><!--end #menubar-->
    <!-- END MENUBAR -->
    {% endblock menubar %}
    </div><!--end #base-->
<!-- END BASE -->

    {% include "layouts/admin/include/javascript.html" %}
    <script type="text/javascript">
        $(function(){
            {% if messages %}
            toastr.clear();
            {% for message in messages %}
            toastr.options.closeButton = true;
            toastr.options.progressBar = true;
            toastr.options.debug = false;
            toastr.options.positionClass = 'toast-bottom-right';
            toastr.options.showDuration = 333;
            toastr.options.hideDuration = 333;
            toastr.options.timeOut = 4000;
            toastr.options.extendedTimeOut = 4000;
            toastr.options.showEasing = 'swing';
            toastr.options.hideEasing = 'swing';
            toastr.options.showMethod = 'slideDown';
            toastr.options.hideMethod = 'slideUp';
            toastr.{{message.tags}}('{{message}}', '');
            {% endfor %}
            {% endif %}
        });

    </script>
    {% block extra_js %}
    {% endblock extra_js %}
</body>
</html>